// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTib8ljSmMGCc28xIR9Q1we7qKqkrc7Z4',
    appId: '1:395879090318:web:c95b214f6ecae45a0761df',
    messagingSenderId: '395879090318',
    projectId: 'caresync-76e4e',
    authDomain: 'caresync-76e4e.firebaseapp.com',
    storageBucket: 'caresync-76e4e.firebasestorage.app',
    measurementId: 'G-4H9PT81FFV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7UP3JbAwAj0gv6EYFQn-0C0XOpSSy2XQ',
    appId: '1:395879090318:ios:c4b5934f47958b1b0761df',
    messagingSenderId: '395879090318',
    projectId: 'caresync-76e4e',
    storageBucket: 'caresync-76e4e.firebasestorage.app',
    iosBundleId: 'com.example.caresync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7UP3JbAwAj0gv6EYFQn-0C0XOpSSy2XQ',
    appId: '1:395879090318:ios:c4b5934f47958b1b0761df',
    messagingSenderId: '395879090318',
    projectId: 'caresync-76e4e',
    storageBucket: 'caresync-76e4e.firebasestorage.app',
    iosBundleId: 'com.example.caresync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTib8ljSmMGCc28xIR9Q1we7qKqkrc7Z4',
    appId: '1:395879090318:web:29634b74cf4638c40761df',
    messagingSenderId: '395879090318',
    projectId: 'caresync-76e4e',
    authDomain: 'caresync-76e4e.firebaseapp.com',
    storageBucket: 'caresync-76e4e.firebasestorage.app',
    measurementId: 'G-9YEZW2CX0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuKbaEur2QegJPI7VLfrCIguY4bg2oLY4',
    appId: '1:395879090318:android:e85341ba3ddd99bc0761df',
    messagingSenderId: '395879090318',
    projectId: 'caresync-76e4e',
    storageBucket: 'caresync-76e4e.firebasestorage.app',
  );
}